"""Added new column to Project history, storyboard history

Revision ID: 11b8d6f6c87b
Revises: 90a3d8bc23b5
Create Date: 2025-01-26 10:11:40.057059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b8d6f6c87b'
down_revision: Union[str, None] = '90a3d8bc23b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_history', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_history', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
