"""Add forin keys to project storyboard

Revision ID: 1b6fa3a1d4e2
Revises: 83aaeb791df2
Create Date: 2024-05-08 16:42:50.738923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6fa3a1d4e2'
down_revision: Union[str, None] = '83aaeb791df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboards', sa.Column('project_id', sa.UUID(), nullable=False))
    op.drop_constraint('storyboards_project_fkey', 'storyboards', type_='foreignkey')
    op.create_foreign_key(None, 'storyboards', 'projects', ['project_id'], ['id'])
    op.drop_column('storyboards', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboards', sa.Column('project', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'storyboards', type_='foreignkey')
    op.create_foreign_key('storyboards_project_fkey', 'storyboards', 'projects', ['project'], ['id'])
    op.drop_column('storyboards', 'project_id')
    # ### end Alembic commands ###
