"""Added new column to Project history, storyboard history

Revision ID: 25bfa57e66e8
Revises: 87894c2cc192
Create Date: 2025-01-25 11:34:50.579411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bfa57e66e8'
down_revision: Union[str, None] = '87894c2cc192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
