"""Added order to storyboard

Revision ID: 34c2757aa2b0
Revises: 1b6fa3a1d4e2
Create Date: 2024-06-12 13:04:28.747316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c2757aa2b0'
down_revision: Union[str, None] = '1b6fa3a1d4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboards', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storyboards', 'order')
    # ### end Alembic commands ###
