"""Added new column to Project

Revision ID: 38a1625b41b7
Revises: 
Create Date: 2024-06-24 13:30:54.023745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a1625b41b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspect_ratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('boards_per_mins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('code_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('count'),
    sa.UniqueConstraint('name')
    )
    op.create_table('script_styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storyboard_styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('video_durations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('synopsis', sa.String(length=2500), nullable=True),
    sa.Column('script', sa.String(length=25000), nullable=True),
    sa.Column('script_style_id', sa.UUID(), nullable=True),
    sa.Column('storyboard_style_id', sa.UUID(), nullable=True),
    sa.Column('video_duration_id', sa.UUID(), nullable=True),
    sa.Column('aspect_ratio_id', sa.UUID(), nullable=True),
    sa.Column('boards_per_min_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_ratio_id'], ['aspect_ratios.id'], ),
    sa.ForeignKeyConstraint(['boards_per_min_id'], ['boards_per_mins.id'], ),
    sa.ForeignKeyConstraint(['script_style_id'], ['script_styles.id'], ),
    sa.ForeignKeyConstraint(['storyboard_style_id'], ['storyboard_styles.id'], ),
    sa.ForeignKeyConstraint(['video_duration_id'], ['video_durations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=25000), nullable=True),
    sa.Column('scene_description', sa.String(length=25000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storyboards')
    op.drop_table('projects')
    op.drop_table('video_durations')
    op.drop_table('storyboard_styles')
    op.drop_table('script_styles')
    op.drop_table('boards_per_mins')
    op.drop_table('aspect_ratios')
    # ### end Alembic commands ###
