"""make synopsis unmandatory

Revision ID: 51058a9b697d
Revises: e96efbe7fb3e
Create Date: 2024-09-01 16:12:07.714810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51058a9b697d'
down_revision: Union[str, None] = 'e96efbe7fb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
