"""Add description to AspectRatio

Revision ID: 60e8f7fcea67
Revises: 11b8d6f6c87b
Create Date: 2025-02-17 12:11:41.498911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e8f7fcea67'
down_revision: Union[str, None] = '11b8d6f6c87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspect_ratios', sa.Column('description', sa.String(length=350), nullable=True))
    op.create_unique_constraint(None, 'aspect_ratios', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aspect_ratios', type_='unique')
    op.drop_column('aspect_ratios', 'description')
    # ### end Alembic commands ###
