"""Added new description to storyboard style

Revision ID: 730ad670826a
Revises: aaa372a8f016
Create Date: 2024-10-28 14:22:02.360912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730ad670826a'
down_revision: Union[str, None] = 'aaa372a8f016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboard_styles', sa.Column('description', sa.String(length=150), nullable=True))
    op.drop_column('storyboard_styles', 'Description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboard_styles', sa.Column('Description', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('storyboard_styles', 'description')
    # ### end Alembic commands ###
