"""Added new column status to Project

Revision ID: 77a01d660995
Revises: c520376f02fd
Create Date: 2024-08-20 14:59:23.105563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a01d660995'
down_revision: Union[str, None] = 'c520376f02fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('projects', sa.Column('status_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'status_id')
    op.drop_table('status')
    # ### end Alembic commands ###
