"""Add forin keys to project

Revision ID: 83aaeb791df2
Revises: 6a303a153aa0
Create Date: 2024-05-08 16:24:04.493704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83aaeb791df2'
down_revision: Union[str, None] = '6a303a153aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('storyboard_style_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('video_duration_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('aspect_ratio_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('boards_per_min_id', sa.UUID(), nullable=True))
    op.drop_constraint('projects_boards_per_min_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_storyboard_style_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_aspect_ratio_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_VideoDuration_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'video_durations', ['video_duration_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'storyboard_styles', ['storyboard_style_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'boards_per_mins', ['boards_per_min_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'aspect_ratios', ['aspect_ratio_id'], ['id'])
    op.drop_column('projects', 'aspect_ratio')
    op.drop_column('projects', 'test')
    op.drop_column('projects', 'storyboard_style')
    op.drop_column('projects', 'boards_per_min')
    op.drop_column('projects', 'VideoDuration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('VideoDuration', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('boards_per_min', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('storyboard_style', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('test', sa.VARCHAR(length=2500), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('aspect_ratio', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_VideoDuration_fkey', 'projects', 'video_durations', ['VideoDuration'], ['id'])
    op.create_foreign_key('projects_aspect_ratio_fkey', 'projects', 'aspect_ratios', ['aspect_ratio'], ['id'])
    op.create_foreign_key('projects_storyboard_style_fkey', 'projects', 'storyboard_styles', ['storyboard_style'], ['id'])
    op.create_foreign_key('projects_boards_per_min_fkey', 'projects', 'boards_per_mins', ['boards_per_min'], ['id'])
    op.drop_column('projects', 'boards_per_min_id')
    op.drop_column('projects', 'aspect_ratio_id')
    op.drop_column('projects', 'video_duration_id')
    op.drop_column('projects', 'storyboard_style_id')
    # ### end Alembic commands ###
