"""Added new column to Project history, storyboard history

Revision ID: 87894c2cc192
Revises: 730ad670826a
Create Date: 2025-01-20 22:05:32.563039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87894c2cc192'
down_revision: Union[str, None] = '730ad670826a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('synopsis', sa.String(length=2500), nullable=True),
    sa.Column('script', sa.String(length=25000), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('script_style_id', sa.UUID(), nullable=True),
    sa.Column('storyboard_style_id', sa.UUID(), nullable=True),
    sa.Column('video_duration_id', sa.UUID(), nullable=True),
    sa.Column('aspect_ratio_id', sa.UUID(), nullable=True),
    sa.Column('boards_per_min_id', sa.UUID(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_ratio_id'], ['aspect_ratios.id'], ),
    sa.ForeignKeyConstraint(['boards_per_min_id'], ['boards_per_mins.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['script_style_id'], ['script_styles.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['storyboard_style_id'], ['storyboard_styles.id'], ),
    sa.ForeignKeyConstraint(['video_duration_id'], ['video_durations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboards_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_history_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=25000), nullable=True),
    sa.Column('scene_description', sa.String(length=25000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_history_id'], ['projects_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storyboards_history')
    op.drop_table('projects_history')
    # ### end Alembic commands ###
