"""Added new column to Project history, storyboard history

Revision ID: 90a3d8bc23b5
Revises: ad81549899f2
Create Date: 2025-01-26 09:42:15.698714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a3d8bc23b5'
down_revision: Union[str, None] = 'ad81549899f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
