"""Added order to storyboard

Revision ID: 9911f9993b59
Revises: 34c2757aa2b0
Create Date: 2024-06-12 13:18:41.292580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9911f9993b59'
down_revision: Union[str, None] = '34c2757aa2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storyboards', 'image',
               existing_type=sa.VARCHAR(length=2500),
               type_=sa.String(length=25000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storyboards', 'image',
               existing_type=sa.String(length=25000),
               type_=sa.VARCHAR(length=2500),
               existing_nullable=True)
    # ### end Alembic commands ###
