"""Added new column to Project history, storyboard history

Revision ID: ad81549899f2
Revises: 6badab8d5285
Create Date: 2025-01-26 09:37:30.241026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad81549899f2'
down_revision: Union[str, None] = '6badab8d5285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboards_history', sa.Column('projects_history_id', sa.UUID(), nullable=False))
    op.drop_constraint('storyboards_history_project_history_id_fkey', 'storyboards_history', type_='foreignkey')
    op.create_foreign_key(None, 'storyboards_history', 'projects_history', ['projects_history_id'], ['id'])
    op.drop_column('storyboards_history', 'project_history_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboards_history', sa.Column('project_history_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'storyboards_history', type_='foreignkey')
    op.create_foreign_key('storyboards_history_project_history_id_fkey', 'storyboards_history', 'projects_history', ['project_history_id'], ['id'])
    op.drop_column('storyboards_history', 'projects_history_id')
    # ### end Alembic commands ###
