"""Create Error Tables

Revision ID: d4d3962bd532
Revises: 38a1625b41b7
Create Date: 2024-07-08 00:47:44.003742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d3962bd532'
down_revision: Union[str, None] = '38a1625b41b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t2i_operation_error',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('script_text', sa.String(length=10000), nullable=True),
    sa.Column('error', sa.String(length=25000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2t_operation_error',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('script_text', sa.String(length=10000), nullable=True),
    sa.Column('error', sa.String(length=25000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('storyboards', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storyboards', 'created_date')
    op.drop_column('projects', 'created_date')
    op.drop_table('t2t_operation_error')
    op.drop_table('t2i_operation_error')
    # ### end Alembic commands ###
