"""Added new column status to Project

Revision ID: e96efbe7fb3e
Revises: 77a01d660995
Create Date: 2024-08-20 15:01:50.659690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96efbe7fb3e'
down_revision: Union[str, None] = '77a01d660995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
