"""Added new description to storyboard style

Revision ID: f35875fd7d0d
Revises: ecdf1498fe58
Create Date: 2024-10-28 14:18:23.148194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35875fd7d0d'
down_revision: Union[str, None] = 'ecdf1498fe58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyboard_styles', sa.Column('Description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storyboard_styles', 'Description')
    # ### end Alembic commands ###
