"""add order to storyboards table

Revision ID: 77127c0589ee
Revises: d1df1d874025
Create Date: 2024-05-17 15:10:07.873509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77127c0589ee'
down_revision: Union[str, None] = 'd1df1d874025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text2text_operation_storyboard', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text2text_operation_storyboard', 'order')
    # ### end Alembic commands ###
