"""init

Revision ID: 8fdef480fbaf
Revises: 28566b6c45ef
Create Date: 2024-05-16 10:14:44.160884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdef480fbaf'
down_revision: Union[str, None] = '28566b6c45ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text2text_operation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('original_text', sa.String(length=10000), nullable=True),
    sa.Column('generated_text', sa.String(length=10000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_text'),
    sa.UniqueConstraint('original_text'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text2text_operation')
    # ### end Alembic commands ###
