"""operation error

Revision ID: 966ca5ae3df4
Revises: e558e2730516
Create Date: 2024-07-15 19:53:09.526049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966ca5ae3df4'
down_revision: Union[str, None] = 'e558e2730516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_error',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('script_text', sa.String(length=10000), nullable=True),
    sa.Column('error', sa.String(length=25000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_error')
    # ### end Alembic commands ###
