"""init

Revision ID: a5725fb92b58
Revises: 
Create Date: 2024-06-24 13:42:52.352047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5725fb92b58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text2text_operation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('original_text', sa.String(length=10000), nullable=True),
    sa.Column('generated_text', sa.String(length=10000), nullable=True),
    sa.Column('generated_script', sa.String(length=10000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text2text_operation_storyboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text2text_operation_id', sa.UUID(), nullable=False),
    sa.Column('generated_text', sa.String(length=10000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['text2text_operation_id'], ['text2text_operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text2text_operation_storyboard')
    op.drop_table('text2text_operation')
    # ### end Alembic commands ###
