"""Added new column to Project

Revision ID: bdb796f364c3
Revises: 77127c0589ee
Create Date: 2024-05-20 12:03:07.374696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb796f364c3'
down_revision: Union[str, None] = '77127c0589ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('text2text_operation_reference_key', 'text2text_operation', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('text2text_operation_reference_key', 'text2text_operation', ['reference'])
    # ### end Alembic commands ###
