"""operation error

Revision ID: cf0d9538a371
Revises: 966ca5ae3df4
Create Date: 2024-07-15 19:58:15.826904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0d9538a371'
down_revision: Union[str, None] = '966ca5ae3df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text2text_operation_storyboard', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text2text_operation_storyboard', 'created_date')
    # ### end Alembic commands ###
