"""Added new column to Project

Revision ID: f5eba171202d
Revises: bdb796f364c3
Create Date: 2024-05-20 12:07:24.295711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eba171202d'
down_revision: Union[str, None] = 'bdb796f364c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('text2text_operation_generated_script_key', 'text2text_operation', type_='unique')
    op.drop_constraint('text2text_operation_generated_text_key', 'text2text_operation', type_='unique')
    op.drop_constraint('text2text_operation_original_text_key', 'text2text_operation', type_='unique')
    op.drop_constraint('text2text_operation_storyboard_generated_text_key', 'text2text_operation_storyboard', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('text2text_operation_storyboard_generated_text_key', 'text2text_operation_storyboard', ['generated_text'])
    op.create_unique_constraint('text2text_operation_original_text_key', 'text2text_operation', ['original_text'])
    op.create_unique_constraint('text2text_operation_generated_text_key', 'text2text_operation', ['generated_text'])
    op.create_unique_constraint('text2text_operation_generated_script_key', 'text2text_operation', ['generated_script'])
    # ### end Alembic commands ###
