
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_NODENAME=my-rabbit
      # - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      # - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always

volumes:
  rabbitmq_data:
    external: false
