"""T2I database

Revision ID: 6685dfa32cf4
Revises: 
Create Date: 2024-05-21 09:42:28.529044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6685dfa32cf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text2image_operation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('reference', sa.String(
                        length=50), nullable=True),
                    sa.Column('script_text', sa.String(
                        length=10000), nullable=True),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('text2image_operation_image',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('text2image_operation_id',
                              sa.UUID(), nullable=False),
                    sa.Column('scene_text', sa.String(
                        length=10000), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('url', sa.String(length=250), nullable=True),
                    sa.ForeignKeyConstraint(['text2image_operation_id'], [
                        'text2image_operation.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_table('text2image_operation_image')
    op.drop_table('text2image_operation')
    # ### end Alembic commands ###
