"""Added new column to Project

Revision ID: faa0a66ebf98
Revises: 6685dfa32cf4
Create Date: 2024-07-05 14:46:55.250923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa0a66ebf98'
down_revision: Union[str, None] = '6685dfa32cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_error',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('script_text', sa.String(length=10000), nullable=True),
    sa.Column('error', sa.String(length=25000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('text2image_operation_image', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text2image_operation_image', 'created_date')
    op.drop_table('operation_error')
    # ### end Alembic commands ###
